FROM python:3.12-slim

WORKDIR /app
COPY bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY bot/ ./bot/
COPY storage/ ./storage/
COPY config.py ./
CMD ["python", "bot/main.py"]
